// client/src/pages/Library.tsx - Fixed library component to display auto-saved workouts

import React, { useState, useEffect } from 'react';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Clock, Flame, Dumbbell, Bot, User, Trash2 } from 'lucide-react';
import { useLocation } from 'wouter';

interface Workout {
  id: number;
  name: string;
  description: string;
  duration: number;
  difficulty: string;
  createdBy: string;
  autoGenerated: boolean;
  metadata: {
    exercises: {
      warmup: any[];
      main: any[];
      cooldown: any[];
    };
    generationParams?: any;
    aiModel?: string;
  };
  tags: string[];
  estimatedCalories: number;
  targetMuscleGroups: string[];
  analytics: {
    timesCompleted: number;
    lastCompleted: string | null;
  };
  createdAt: string;
}

export default function Library() {
  const [workouts, setWorkouts] = useState<Workout[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [, setLocation] = useLocation();

  useEffect(() => {
    fetchWorkouts();
  }, []);

  // Add a useEffect to refetch when the page becomes visible
  useEffect(() => {
    const handleFocus = () => {
      fetchWorkouts();
    };
    
    window.addEventListener('focus', handleFocus);
    return () => window.removeEventListener('focus', handleFocus);
  }, []);

  const fetchWorkouts = async () => {
    try {
      setLoading(true);
      setError(null);
      
      const response = await fetch('/api/workouts');
      
      if (!response.ok) {
        throw new Error(`Failed to fetch workouts: ${response.statusText}`);
      }
      
      const data = await response.json();
      console.log('Fetched workouts:', data);
      
      // Ensure data is an array
      const workoutList = Array.isArray(data) ? data : data.workouts || [];
      
      // Sort by creation date, newest first
      workoutList.sort((a, b) => 
        new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
      );
      
      setWorkouts(workoutList);
    } catch (err) {
      console.error('Error fetching workouts:', err);
      setError(err.message || 'Failed to load workouts');
    } finally {
      setLoading(false);
    }
  };

  const startWorkout = (workout: Workout) => {
    // Navigate to workout player with the workout data
    setLocation(`/workout/${workout.id}`);
  };

  const deleteWorkout = async (workoutId: number, workoutName: string) => {
    if (!confirm(`Are you sure you want to delete "${workoutName}"? This action cannot be undone.`)) {
      return;
    }

    try {
      const response = await fetch(`/api/workouts/${workoutId}`, {
        method: 'DELETE',
      });

      if (!response.ok) {
        throw new Error('Failed to delete workout');
      }

      // Remove workout from local state
      setWorkouts(workouts.filter(w => w.id !== workoutId));
      
      // Show success message
      console.log(`Workout "${workoutName}" deleted successfully`);
    } catch (err) {
      console.error('Error deleting workout:', err);
      alert('Failed to delete workout. Please try again.');
    }
  };

  const getDifficultyColor = (difficulty: string) => {
    switch (difficulty.toLowerCase()) {
      case 'beginner':
        return 'bg-green-500';
      case 'intermediate':
        return 'bg-yellow-500';
      case 'advanced':
        return 'bg-red-500';
      default:
        return 'bg-gray-500';
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-primary"></div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="text-center py-8">
        <p className="text-red-500 mb-4">{error}</p>
        <Button onClick={fetchWorkouts}>Try Again</Button>
      </div>
    );
  }

  if (workouts.length === 0) {
    return (
      <div className="text-center py-12">
        <Bot className="mx-auto h-16 w-16 text-gray-400 mb-4" />
        <h3 className="text-xl font-semibold mb-2">No workouts yet</h3>
        <p className="text-gray-500 mb-6">
          Ask your AI trainer to create your first workout!
        </p>
        <Button onClick={() => setLocation('/ai-trainer')}>
          Go to AI Trainer
        </Button>
      </div>
    );
  }

  return (
    <div className="space-y-4 pb-20">
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-2xl font-bold">My Workouts</h1>
        <Badge variant="outline" className="text-sm">
          {workouts.length} workout{workouts.length !== 1 ? 's' : ''}
        </Badge>
      </div>

      {workouts.map((workout) => (
        <Card key={workout.id} className="overflow-hidden">
          <CardHeader>
            <div className="flex justify-between items-start">
              <div className="flex-1">
                <CardTitle className="flex items-center gap-2">
                  {workout.name}
                  {workout.autoGenerated && (
                    <Badge variant="secondary" className="ml-2">
                      <Bot className="w-3 h-3 mr-1" />
                      AI Generated
                    </Badge>
                  )}
                </CardTitle>
                <CardDescription className="mt-1">
                  {workout.description}
                </CardDescription>
              </div>
              <Badge className={getDifficultyColor(workout.difficulty)}>
                {workout.difficulty}
              </Badge>
            </div>
          </CardHeader>
          
          <CardContent>
            <div className="grid grid-cols-3 gap-4 mb-4">
              <div className="flex items-center gap-2 text-sm text-gray-600">
                <Clock className="w-4 h-4" />
                <span>{workout.duration} min</span>
              </div>
              <div className="flex items-center gap-2 text-sm text-gray-600">
                <Flame className="w-4 h-4" />
                <span>{workout.estimatedCalories} cal</span>
              </div>
              <div className="flex items-center gap-2 text-sm text-gray-600">
                <Dumbbell className="w-4 h-4" />
                <span>{workout.analytics.timesCompleted}x</span>
              </div>
            </div>

            {/* Exercise breakdown */}
            {workout.metadata?.exercises && (
              <div className="text-sm text-gray-600 mb-4">
                <span className="font-medium">Exercises:</span>{' '}
                {workout.metadata.exercises.warmup.length} warmup,{' '}
                {workout.metadata.exercises.main.length} main,{' '}
                {workout.metadata.exercises.cooldown.length} cooldown
              </div>
            )}

            {/* Tags */}
            {workout.tags && workout.tags.length > 0 && (
              <div className="flex flex-wrap gap-2 mb-4">
                {workout.tags.map((tag, index) => (
                  <Badge key={index} variant="outline" className="text-xs">
                    #{tag}
                  </Badge>
                ))}
              </div>
            )}

            {/* Muscle groups */}
            {workout.targetMuscleGroups && workout.targetMuscleGroups.length > 0 && (
              <div className="text-sm text-gray-600 mb-4">
                <span className="font-medium">Targets:</span>{' '}
                {workout.targetMuscleGroups.join(', ')}
              </div>
            )}

            <div className="flex gap-2">
              <Button 
                onClick={() => startWorkout(workout)}
                className="flex-1"
              >
                Start Workout
              </Button>
              <Button 
                variant="outline"
                onClick={() => setLocation(`/workout/${workout.id}/details`)}
              >
                View Details
              </Button>
              <Button 
                variant="outline"
                size="icon"
                onClick={() => deleteWorkout(workout.id, workout.name)}
                className="text-red-500 hover:text-red-700 hover:bg-red-50"
              >
                <Trash2 className="w-4 h-4" />
              </Button>
            </div>
          </CardContent>
        </Card>
      ))}
    </div>
  );
}