// shared/schema.ts - Updated workout schema with all necessary fields

import { pgTable, text, serial, timestamp, integer, jsonb, boolean, json } from 'drizzle-orm/pg-core';
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  username: text("username").notNull().unique(),
  password: text("password").notNull(),
  name: text("name"),
  plan: text("plan").default("Standard"),
});

export const workouts = pgTable('workouts', {
  id: serial('id').primaryKey(),
  userId: text('user_id').notNull(),
  name: text('name').notNull(),
  description: text('description'),
  duration: integer('duration').notNull(), // in minutes
  difficulty: text('difficulty').notNull(), // beginner, intermediate, advanced
  
  // Auto-save specific fields
  createdBy: text('created_by').default('user'), // 'user' or 'ai-agent'
  autoGenerated: boolean('auto_generated').default(false),
  
  // Rich metadata as JSONB
  metadata: jsonb('metadata').default({
    generationParams: {},
    exercises: {
      warmup: [],
      main: [],
      cooldown: []
    },
    version: '1.0',
    aiModel: null
  }),
  
  // Categorization
  tags: text('tags').array().default([]),
  estimatedCalories: integer('estimated_calories'),
  targetMuscleGroups: text('target_muscle_groups').array().default([]),
  
  // Analytics
  analytics: jsonb('analytics').default({
    timesCompleted: 0,
    lastCompleted: null,
    averageRating: null,
    feedback: []
  }),
  
  // Timestamps
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow()  
});

export const exercises = pgTable("exercises", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
  targetMuscle: text("target_muscle"),
  formGuide: text("form_guide"),
});

export const workoutExercises = pgTable("workout_exercises", {
  id: serial("id").primaryKey(),
  workoutId: integer("workout_id").notNull(),
  exerciseId: integer("exercise_id").notNull(),
  sets: integer("sets").notNull(),
  reps: integer("reps").notNull(),
  weight: integer("weight"),
  duration: integer("duration"),
});

export const progressEntries = pgTable("progress_entries", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull(),
  exerciseId: integer("exercise_id").notNull(),
  value: integer("value").notNull(),
  unit: text("unit").notNull(),
  date: timestamp("date").defaultNow(),
});

export const aiConversations = pgTable("ai_conversations", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull(),
  messages: json("messages").notNull().$type<MessageEntry[]>(),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// Message types for AI trainer
export type MessageRole = "user" | "assistant" | "system";

export interface MessageEntry {
  role: MessageRole;
  content: string;
  timestamp: string;
}

export interface MessageRequest {
  message: string;
  conversationId?: number;
}

export interface MessageResponse {
  message: MessageEntry;
  conversationId: number;
  workout?: any;
  exerciseForm?: any;
  progressData?: any;
}

// Insert schemas
export const insertUserSchema = createInsertSchema(users).pick({
  username: true,
  password: true,
  name: true,
  plan: true,
});

export const insertWorkoutSchema = createInsertSchema(workouts);

export const insertExerciseSchema = createInsertSchema(exercises).pick({
  name: true,
  description: true,
  targetMuscle: true,
  formGuide: true,
});

export const insertWorkoutExerciseSchema = createInsertSchema(workoutExercises).pick({
  workoutId: true,
  exerciseId: true,
  sets: true,
  reps: true,
  weight: true,
  duration: true,
});

export const insertProgressEntrySchema = createInsertSchema(progressEntries).pick({
  userId: true,
  exerciseId: true,
  value: true,
  unit: true,
});

export const insertAiConversationSchema = createInsertSchema(aiConversations).pick({
  userId: true,
  messages: true,
});

// Types
export type InsertUser = z.infer<typeof insertUserSchema>;
export type User = typeof users.$inferSelect;

export type Workout = typeof workouts.$inferSelect;
export type NewWorkout = typeof workouts.$inferInsert;
export type InsertWorkout = z.infer<typeof insertWorkoutSchema>;

export type InsertExercise = z.infer<typeof insertExerciseSchema>;
export type Exercise = typeof exercises.$inferSelect;

export type InsertWorkoutExercise = z.infer<typeof insertWorkoutExerciseSchema>;
export type WorkoutExercise = typeof workoutExercises.$inferSelect;

export type InsertProgressEntry = z.infer<typeof insertProgressEntrySchema>;
export type ProgressEntry = typeof progressEntries.$inferSelect;

export type InsertAiConversation = z.infer<typeof insertAiConversationSchema>;
export type AiConversation = typeof aiConversations.$inferSelect;
